# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"say_hi": "00_core.ipynb",
         "hiSayer": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://fastai.github.io/nbdev_tutorial/"

git_url = "https://github.com/fastai/nbdev_tutorial/tree/master/"

def custom_doc_links(name): return None
