# AUTOGENERATED! DO NOT EDIT! File to edit: 00_core.ipynb (unless otherwise specified).

__all__ = ['say_hi', 'hiSayer']

# Cell
def say_hi(to):
    """Say hi to someone"""
    return f'Hi {to}!'

# Cell
class hiSayer:

    def __init__(self, to):
        self.to = to

    def say(self):
        """calls fn `say_hi`"""
        return say_hi(self.to)